apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage-demo/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: michael@cpossibilities.com
  lifecycle: experimental
